### ISSUE TITLE
object compiletime is not a member of package org.emergentorder

### ISSUE THREAD

**Issue by novakov-alexey** [EmergentOrder/onnx-scala#202]
SBT cannot compile example code:
![Screenshot 2021-05-08 at 17 25 21](https://user-images.githubusercontent.com/11204284/117544568-608a8700-b022-11eb-8b23-26889fede8e5.png)
![Screenshot 2021-05-08 at 17 26 46](https://user-images.githubusercontent.com/11204284/117544610-929be900-b022-11eb-9b7a-4a9db9390af2.png)

Do I need to add published modules to my build dependencies? I tried with other modules, but same issue:

```scala
import $ivy.`org.emergent-order::onnx-scala-backends:0.13.0`
import $ivy.`org.emergent-order::onnx-scala-common:0.13.0`
import $ivy.`org.emergent-order::onnx-scala:0.13.0`
```

Scastie example:
https://scastie.scala-lang.org/novakov-alexey/Eg9Hn0dVRsSNCt3OwzmdMg/1

**Comment by EmergentOrder** [comment]
Thanks for your interest in the library.
The examples are written in Scala 3, mentioned this in the README.
