### ISSUE TITLE
Platform not supported exception

### ISSUE THREAD

**Issue by bharadwaj221** [EmergentOrder/onnx-scala#32]
Hi,

I am trying to setup ONNX-scala on my windows machine. I am getting the following error:
ONNX Model Evaluation Sample
Exception in thread "main" java.lang.reflect.InvocationTargetException

**Caused by: java.lang.UnsatisfiedLinkError: Platform "windows-x86_64" not supported by class org.bytedeco.ngraph.Backend
	at org.bytedeco.javacpp.Loader.load(Loader.java:1081)
	at org.bytedeco.javacpp.Loader.load(Loader.java:1042)
	at org.bytedeco.ngraph.Backend.<clinit>(Backend.java:19)**
	at org.emergentorder.onnx.backends.NGraphOperatorBackend$class.$init$(NGraphOperatorBackend.scala:43)
	at org.emergentorder.onnx.backends.NGraphModelBackend.<init>(NGraphModelBackend.scala:11)
	at Scripts.SampleScripts.OnnxModelEvaluation$.main(OnnxModelEvaluation.scala:16)
	at Scripts.SampleScripts.OnnxModelEvaluation.main(OnnxModelEvaluation.scala)

Hence, I just wanted to check if Windows is not supported or if there is any workaround for running this in a Windows environment

**Comment by EmergentOrder** [comment]
Windows is not supported by nGraph, which is currently the only supported backend.
I am planning to add a new backend based on ONNX Runtime (which does support Windows).

**Comment by PKHeb** [comment]
Is there any plan to support this on windows, as we plan to take dependency on this to run onnx models via spark which is hosted on Windows. Any other suggestions to do this would also be great :)

**Comment by EmergentOrder** [comment]
As I mentioned, I'll be adding an ONNX Runtime backend using in the near future, which should allow this to work on Windows. There were a few issues with the JavaCPP Preset I'll be using for that have been fixed recently.

**Comment by EmergentOrder** [comment]
@PKHeb The ONNX Runtime (ORT) backed is now in place, used in the readme. 
Can you try again using ORTModelBackend (see the README) ?

**Comment by PKHeb** [comment]
Thankyou @EmergentOrder , i see the changes are not published to the maven repo. I 'll try and enlist it locally and test it out.

**Comment by EmergentOrder** [comment]
Ok, let me know how it goes.
I plan to publish a new release in a few weeks, after the next ONNX and Dotty releases.

**Comment by PKHeb** [comment]
thanks.  I am able to run examples given on my local windows machine after doing an sbt publishLocal. we should be good :), Would it be possible to release this with the current ONNX release?

**Comment by EmergentOrder** [comment]
In case you are concerned about running older models, it shouldn't be a problem.
Otherwise, there are a few more changes I want to make before I release.

**Comment by PKHeb** [comment]
sure, that should be fine. keep us posted when you release

**Comment by EmergentOrder** [comment]
@PKHeb @bharadwaj221 Version 0.3.0 has been released
