### ISSUE TITLE
why not use onnxruntime's Java API?

### ISSUE THREAD

**Issue by Zhen-hao** [EmergentOrder/onnx-scala#96]
Hi,

This is just a question. Feel free to close it. 

It seems that onnxruntime has a Java API since 1.3.0. 
My question is whether there is a plan to adopt the native API. 
Or are there other good reasons to use `javacpp-presets`? 

Best,
Zhenhao

**Comment by EmergentOrder** [comment]
I just moved to the official Java API.
The result was both a decent speed boost and cleaner interaction w/ ORT.
There are other reasons to use JavaCPP (relatively smooth interoperability between multiple native libs, for example)
The JavaCPP preset served this project well, but the time has come.

**Comment by neboduus** [comment]
Does this mean that you are inviting people to use Java API (https://github.com/microsoft/onnxruntime/blob/master/docs/Java_API.md) ? instead of this repository? I am looking for a solution to run my ONNX NN model into a Scala 2.11 Play app.

**Comment by EmergentOrder** [comment]
Not what I meant, although if all you want is full model inference, you could do that.
I just meant that I am now using the Java API under the hood here.
This repo also offers a fine-grained API (see the README), useful for other tasks, which the Java API does not.
However, we only support Scala 2.13 & 3 (dotty). Is there a reason you can't use 2.13?

**Comment by neboduus** [comment]
Yes, the application has too many dependencies which rely on 2.11 and a migration would mean too much changes to the code base. Given that this lib does not support my Scala version, do you think is possible to simply use Java API instead?

**Comment by EmergentOrder** [comment]
As I said, sure, it is possible.
I would strongly encourage you to move up from 2.11 though, there are no further releases / support planned, so it is effectively end of life.

**Comment by neboduus** [comment]
Thanks a lot for your replies! Yes, we need to plan the migration and I hope we will be able to do that soon!
